[package]
name = "drivechain-c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.28.1"
drivechain = { git = "https://github.com/nchashch/drivechain", rev = "b4efe8a6972503dc11fe1ac64331bd7248b63489" }
hex = "0.4.3"
libc = "0.2.126"

[build-dependencies]
cbindgen = "0.24"
