[package]
name = "drivechain-c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.28.1"
drivechain = { git = "https://github.com/nchashch/drivechain", rev = "56ba8ab0e6e8a1da5cf1bb2cd628f7a2ff195c4f" }
hex = "0.4.3"
libc = "0.2.126"
ureq = { version = "2.4", features = ["json"] }

[build-dependencies]
cbindgen = "0.24"
